#!/bin/bash
# GitHub Secrets Setup Helper Script
# This script helps you configure all necessary GitHub secrets for the awareness platform

echo "=== GitHub Secrets Configuration Helper ==="
echo ""
echo "Please add the following secrets to your GitHub repository:"
echo "Go to: https://github.com/TheMorpheus407/awareness-platform/settings/secrets/actions"
echo ""
echo "=== REQUIRED SECRETS ==="
echo ""
echo "1. SSH_PRIVATE_KEY"
echo "   Description: Private SSH key for server deployment"
echo "   Value: Copy the entire content from bootstrap-awareness private key.txt"
echo "   Including the -----BEGIN RSA PRIVATE KEY----- and -----END RSA PRIVATE KEY----- lines"
echo ""
echo "=== ENVIRONMENT VARIABLES (Add as Repository Variables) ==="
echo "Go to: https://github.com/TheMorpheus407/awareness-platform/settings/variables/actions"
echo ""
echo "2. DB_USER"
echo "   Value: awareness"
echo ""
echo "3. DB_PASSWORD"
echo "   Value: [Generate a secure password - min 16 chars with numbers and symbols]"
echo ""
echo "4. SECRET_KEY"
echo "   Value: [Generate using: openssl rand -hex 32]"
echo ""
echo "5. JWT_SECRET_KEY"
echo "   Value: [Generate using: openssl rand -hex 32]"
echo ""
echo "6. REDIS_PASSWORD"
echo "   Value: [Generate a secure password - min 16 chars]"
echo ""
echo "=== OPTIONAL SECRETS (Can be added later) ==="
echo ""
echo "7. SENDGRID_API_KEY"
echo "   Value: [Get from SendGrid dashboard]"
echo ""
echo "8. STRIPE_SECRET_KEY"
echo "   Value: [Get from Stripe dashboard]"
echo ""
echo "10. STRIPE_PUBLIC_KEY"
echo "    Value: [Get from Stripe dashboard]"
echo ""
echo "11. STRIPE_WEBHOOK_SECRET"
echo "    Value: [Get from Stripe webhook configuration]"
echo ""
echo "12. SENTRY_DSN"
echo "    Value: [Get from Sentry project settings]"
echo ""
echo "=== QUICK COMMANDS TO GENERATE SECRETS ==="
echo ""
echo "# Generate SECRET_KEY:"
echo "openssl rand -hex 32"
echo ""
echo "# Generate JWT_SECRET_KEY:"
echo "openssl rand -hex 32"
echo ""
echo "# Generate secure passwords:"
echo "openssl rand -base64 32 | tr -d '=' | tr '+/' '-_' | cut -c1-24"
echo ""
echo "=== VERIFICATION ==="
echo "After adding secrets, trigger a manual deployment:"
echo "1. Go to: https://github.com/TheMorpheus407/awareness-platform/actions"
echo "2. Select 'Deploy to Production' workflow"
echo "3. Click 'Run workflow' -> 'Run workflow'"
echo ""
echo "Monitor deployment at: https://github.com/TheMorpheus407/awareness-platform/actions"