groups:
  - name: service_alerts
    interval: 30s
    rules:
      # Service Down Alert
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(fastapi_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "Error rate is {{ $value }} errors per second (>5%)"

      # Slow Response Time
      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(fastapi_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Slow API response times"
          description: "95th percentile response time is {{ $value }}s (>1s)"

      # Database Connection Issues
      - alert: DatabaseConnectionError
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "PostgreSQL database is down"
          description: "Cannot connect to PostgreSQL database"

      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% (>80%)"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% (>85%)"

      # Low Disk Space
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space available is {{ $value }}% (<15%)"

      # Container Restart
      - alert: ContainerRestart
        expr: rate(container_last_seen{name!=""}[5m]) > 0
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Container {{ $labels.name }} is restarting"
          description: "Container has restarted {{ $value }} times in the last 5 minutes"

      # SSL Certificate Expiry
      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value | humanizeDuration }}"

      # Endpoint Down
      - alert: EndpointDown
        expr: probe_success == 0
        for: 5m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Endpoint {{ $labels.instance }} is down"
          description: "Endpoint has been unreachable for more than 5 minutes"

  - name: business_alerts
    interval: 1m
    rules:
      # Low Active Users
      - alert: LowActiveUsers
        expr: awareness_active_users < 10
        for: 30m
        labels:
          severity: info
          team: business
        annotations:
          summary: "Low number of active users"
          description: "Only {{ $value }} active users in the last 30 minutes"

      # High Failed Login Rate
      - alert: HighFailedLoginRate
        expr: rate(awareness_login_attempts_total{status="failed"}[5m]) / rate(awareness_login_attempts_total[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High failed login rate"
          description: "Failed login rate is {{ $value | humanizePercentage }}"

      # Course Completion Rate Drop
      - alert: CourseCompletionRateDrop
        expr: rate(awareness_course_completions_total[1h]) < 0.5
        for: 2h
        labels:
          severity: info
          team: business
        annotations:
          summary: "Course completion rate has dropped"
          description: "Course completion rate is {{ $value }} per hour"