server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Backend application logs
  - job_name: backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          service: awareness-platform
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            module: module
            function: function
            line: line
      - labels:
          level:
          module:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Security logs
  - job_name: security
    static_configs:
      - targets:
          - localhost
        labels:
          job: security
          service: awareness-platform
          __path__: /app/logs/security.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: extra.event_type
            user_id: extra.user_id
      - labels:
          event_type:

  # Performance logs
  - job_name: performance
    static_configs:
      - targets:
          - localhost
        labels:
          job: performance
          service: awareness-platform
          __path__: /app/logs/performance.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            issue_type: extra.issue_type
            duration: extra.duration_seconds
      - labels:
          issue_type:

  # Audit logs
  - job_name: audit
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit
          service: awareness-platform
          __path__: /app/logs/audit.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            action: extra.action
            user_id: extra.user_id
            resource: extra.resource
      - labels:
          action:
          resource:

  # Error logs
  - job_name: errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: errors
          service: awareness-platform
          __path__: /app/logs/errors.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            exception_type: exception.type
      - labels:
          exception_type: