"""
Pydantic schemas for the Cybersecurity Awareness Platform API.

This package contains all request/response schemas and data models
used throughout the application.
"""

from .base import (
    BaseSchema,
    PaginatedResponse,
    ErrorResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
)
from .user import (
    UserRole,
    UserBase,
    UserCreate,
    UserUpdate,
    UserProfileUpdate,
    User,
    UserDetail,
    UserListResponse,
    BulkUserResponse,
    BulkUserError,
)
from .company import (
    CompanySize,
    ComplianceRequirement,
    Company,
    CompanyRegistration,
    CompanySettings,
    CompanySettingsUpdate,
    CompanyListResponse,
    PasswordPolicy,
    PhishingFrequency,
    Language,
)
from .course import (
    CourseDifficulty,
    CourseProgressStatus,
    Course,
    CourseDetail,
    AssignedCourse,
    CourseProgress,
    ProgressUpdate,
    QuizQuestion,
    QuizOption,
    QuizAnswer,
    QuizResult,
    QuizFeedback,
)
from .phishing import (
    PhishingDifficulty,
    PhishingCategory,
    CampaignStatus,
    PhishingTemplate,
    PhishingRedFlag,
    Campaign,
    CampaignCreate,
    CampaignDetail,
    CampaignResults,
    CampaignSummary,
    UserPhishingResult,
    CampaignListResponse,
)
from .auth import (
    TokenResponse,
    LoginRequest,
    RefreshTokenRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    VerifyEmailRequest,
    RegistrationResponse,
    TwoFactorSetupRequest,
    TwoFactorSetupResponse,
    TwoFactorVerifyRequest,
    TwoFactorLoginRequest,
    SessionInfo,
    ChangePasswordRequest,
    APIKeyCreate,
    APIKeyResponse,
    AuthenticationLog,
)
from .analytics import (
    ComplianceStatus,
    ComplianceStandard,
    ReportFormat,
    TrendDirection,
    TimeFrame,
    ComplianceReport,
    CompanyMetrics,
    TrainingMetrics,
    PhishingMetrics,
    ComplianceOverview,
    ExecutiveDashboard,
    RiskTrend,
    DepartmentTrend,
    RiskTrends,
    UserRiskProfile,
    SecurityMetrics,
    ReportRequest,
)
from .email_campaign import (
    EmailCampaignStatus,
    EmailTemplate,
    EmailCampaign,
    EmailCampaignCreate,
    EmailCampaignUpdate,
    EmailRecipient,
    EmailCampaignDetail,
    EmailCampaignListResponse,
)


__all__ = [
    # Base schemas
    "BaseSchema",
    "PaginatedResponse",
    "ErrorResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
    # User schemas
    "UserRole",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserProfileUpdate",
    "User",
    "UserDetail",
    "UserListResponse",
    "BulkUserResponse",
    "BulkUserError",
    # Company schemas
    "CompanySize",
    "ComplianceRequirement",
    "Company",
    "CompanyRegistration",
    "CompanySettings",
    "CompanySettingsUpdate",
    "CompanyListResponse",
    "PasswordPolicy",
    "PhishingFrequency",
    "Language",
    # Course schemas
    "CourseDifficulty",
    "CourseProgressStatus",
    "Course",
    "CourseDetail",
    "AssignedCourse",
    "CourseProgress",
    "ProgressUpdate",
    "QuizQuestion",
    "QuizOption",
    "QuizAnswer",
    "QuizResult",
    "QuizFeedback",
    # Phishing schemas
    "PhishingDifficulty",
    "PhishingCategory",
    "CampaignStatus",
    "PhishingTemplate",
    "PhishingRedFlag",
    "Campaign",
    "CampaignCreate",
    "CampaignDetail",
    "CampaignResults",
    "CampaignSummary",
    "UserPhishingResult",
    "CampaignListResponse",
    # Analytics schemas
    "ComplianceStatus",
    "ComplianceStandard",
    "ReportFormat",
    "TrendDirection",
    "TimeFrame",
    "ComplianceReport",
    "CompanyMetrics",
    "TrainingMetrics",
    "PhishingMetrics",
    "ComplianceOverview",
    "ExecutiveDashboard",
    "RiskTrend",
    "DepartmentTrend",
    "RiskTrends",
    "UserRiskProfile",
    "SecurityMetrics",
    "ReportRequest",
    # Email campaign schemas
    "EmailCampaignStatus",
    "EmailTemplate",
    "EmailCampaign",
    "EmailCampaignCreate",
    "EmailCampaignUpdate",
    "EmailRecipient",
    "EmailCampaignDetail",
    "EmailCampaignListResponse",
    # Authentication schemas
    "TokenResponse",
    "LoginRequest",
    "RefreshTokenRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "VerifyEmailRequest",
    "RegistrationResponse",
    "TwoFactorSetupRequest",
    "TwoFactorSetupResponse",
    "TwoFactorVerifyRequest",
    "TwoFactorLoginRequest",
    "SessionInfo",
    "ChangePasswordRequest",
    "APIKeyCreate",
    "APIKeyResponse",
    "AuthenticationLog",
]