#!/bin/bash
set -e

echo "Setting up GitHub secrets for deployment..."
echo ""
echo "Please add the following secrets to your GitHub repository:"
echo "(Settings -> Secrets and variables -> Actions -> New repository secret)"
echo ""
echo "1. SSH_PRIVATE_KEY"
echo "   Copy the entire content from 'bootstrap-awareness private key.txt'"
echo ""
echo "2. DB_PASSWORD"
echo "   Generate a secure password for PostgreSQL"
echo ""
echo "3. REDIS_PASSWORD"
echo "   Generate a secure password for Redis"
echo ""
echo "4. SECRET_KEY"
echo "   Generate a secure secret key (min 32 characters)"
echo "   You can use: openssl rand -hex 32"
echo ""
echo "5. SENDGRID_API_KEY (optional)"
echo "   Get from SendGrid dashboard"
echo ""
echo "6. STRIPE_SECRET_KEY (optional)"
echo "   Get from Stripe dashboard"
echo ""
echo "8. STRIPE_PUBLIC_KEY (optional)"
echo "   Get from Stripe dashboard"
echo ""
echo "9. STRIPE_WEBHOOK_SECRET (optional)"
echo "   Get from Stripe webhook configuration"
echo ""
echo "Once all secrets are added, the GitHub Actions workflow will be able to deploy automatically."