#!/bin/bash
# Helper script to push code to GitHub

echo "=== GitHub Push Helper ==="
echo ""
echo "You have 6 commits ready to push to GitHub."
echo ""
echo "Choose authentication method:"
echo "1. Personal Access Token (Recommended)"
echo "2. GitHub CLI"
echo "3. SSH Key"
echo ""
echo "=== Option 1: Personal Access Token ==="
echo "1. Create token at: https://github.com/settings/tokens"
echo "2. Select scopes: 'repo' and 'workflow'"
echo "3. Run command:"
echo ""
echo "git push https://YOUR_USERNAME:YOUR_TOKEN@github.com/TheMorpheus407/awareness-platform.git main"
echo ""
echo "=== Option 2: GitHub CLI ==="
echo "1. Install GitHub CLI if not already installed"
echo "2. Run: gh auth login"
echo "3. Run: git push origin main"
echo ""
echo "=== Option 3: SSH Key ==="
echo "1. Add your SSH key to GitHub: https://github.com/settings/keys"
echo "2. Run: git remote set-url origin git@github.com:TheMorpheus407/awareness-platform.git"
echo "3. Run: git push origin main"
echo ""
echo "=== Current Git Status ==="
git status --short --branch
echo ""
echo "=== Commits to be pushed ==="
git log --oneline origin/main..HEAD