#!/bin/bash

# Script to help set up GitHub Actions secrets
# Run this locally with appropriate GitHub token

echo "GitHub Actions Setup Guide"
echo "=========================="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo ""
echo "1. PRODUCTION_HOST"
echo "   Value: 83.228.205.20"
echo ""
echo "2. PRODUCTION_USER"
echo "   Value: root (or your deployment user)"
echo ""
echo "3. PRODUCTION_SSH_KEY"
echo "   Value: Content of your private SSH key"
echo "   Get it from: bootstrap-awareness private key.txt"
echo ""
echo "4. PRODUCTION_DATABASE_URL"
echo "   Value: postgresql://awareness_user:YOUR_PASSWORD@postgres:5432/awareness_db"
echo ""
echo "5. PRODUCTION_SECRET_KEY"
echo "   Value: A secure random string (generate with: openssl rand -hex 32)"
echo ""
echo "6. GITHUB_TOKEN is automatically provided by GitHub Actions"
echo ""
echo "To add these secrets:"
echo "1. Go to https://github.com/TheMorpheus407/awareness-platform/settings/secrets/actions"
echo "2. Click 'New repository secret' for each secret"
echo "3. Enter the name and value"
echo ""
echo "Example using GitHub CLI (if you have gh authenticated):"
echo ""
echo "gh secret set PRODUCTION_HOST --body '83.228.205.20'"
echo "gh secret set PRODUCTION_USER --body 'root'"
echo "gh secret set PRODUCTION_SSH_KEY < 'bootstrap-awareness private key.txt'"
echo "gh secret set PRODUCTION_DATABASE_URL --body 'postgresql://awareness_user:PASSWORD@postgres:5432/awareness_db'"
echo "gh secret set PRODUCTION_SECRET_KEY --body \"\$(openssl rand -hex 32)\""