name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Run backend tests
        run: |
          cd backend
          pytest --cov=. --cov-report=xml
      
      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --passWithNoTests

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 83.228.205.20 >> ~/.ssh/known_hosts
      
      - name: Create deployment directory on server
        run: |
          ssh root@83.228.205.20 "mkdir -p /opt/awareness/{backend,frontend,scripts,nginx}"
      
      - name: Copy deployment files
        run: |
          scp docker-compose.prod.yml root@83.228.205.20:/opt/awareness/docker-compose.yml
          scp deployment/scripts/deploy-production.sh root@83.228.205.20:/opt/awareness/scripts/
          scp deployment/nginx/sites-enabled/awareness-platform.conf root@83.228.205.20:/opt/awareness/nginx/
      
      - name: Deploy application
        run: |
          ssh root@83.228.205.20 << 'EOF'
            cd /opt/awareness
            
            # Create .env file
            cat > .env << 'ENVFILE'
            # Database
            DATABASE_URL=postgresql://awareness_user:${DB_PASSWORD}@postgres:5432/awareness_db
            POSTGRES_USER=awareness_user
            POSTGRES_PASSWORD=${DB_PASSWORD}
            POSTGRES_DB=awareness_db
            
            # Application
            SECRET_KEY=${SECRET_KEY}
            ALGORITHM=HS256
            ACCESS_TOKEN_EXPIRE_MINUTES=30
            REFRESH_TOKEN_EXPIRE_DAYS=7
            
            # Email
            SMTP_HOST=smtp.sendgrid.net
            SMTP_PORT=587
            SMTP_USER=apikey
            SMTP_PASSWORD=${SENDGRID_API_KEY}
            EMAIL_FROM=noreply@bootstrap-awareness.de
            
            # Frontend
            VITE_API_URL=https://bootstrap-awareness.de/api
            
            # Redis
            REDIS_URL=redis://redis:6379
            ENVFILE
            
            # Pull latest images
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
            
            # Update docker-compose.yml with correct image names
            sed -i "s|backend:latest|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest|g" docker-compose.yml
            sed -i "s|frontend:latest|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest|g" docker-compose.yml
            
            # Stop existing containers
            docker-compose down
            
            # Start new containers
            docker-compose up -d
            
            # Wait for services to be ready
            sleep 30
            
            # Run database migrations
            docker-compose exec -T backend alembic upgrade head
            
            # Create superuser if not exists
            docker-compose exec -T backend python scripts/create_superuser.py || true
          EOF
      
      - name: Health check
        run: |
          sleep 10
          response=$(curl -s -o /dev/null -w "%{http_code}" https://bootstrap-awareness.de/api/health)
          if [ $response -eq 200 ]; then
            echo "Health check passed"
          else
            echo "Health check failed with status $response"
            exit 1
          fi